"""Ajout du modele sanitaire personnalisable par tenant

Revision ID: 099619ee9090
Revises: 16367f5297ce
Create Date: 2026-09-12 22:29:35.541809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099619ee9090'
down_revision = '16367f5297ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poultry_sanitary_program_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('program_type', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_sanitary_program_template_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_sanitary_program_template_items_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_sanitary_program_template_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_sanitary_program_template_items_tenant_id'))

    op.drop_table('poultry_sanitary_program_template_items')
    # ### end Alembic commands ###
