"""ajout parametres avances du tenant (elevage, alertes, stock, finance, securite)

Revision ID: 1b2bb701dce2
Revises: 956949e92fad
Create Date: 2026-09-15 15:34:15.975343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2bb701dce2'
down_revision = '956949e92fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_breed', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('default_cycle_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fcr_alert_threshold', sa.Numeric(precision=4, scale=2), nullable=True))
        batch_op.add_column(sa.Column(
            'mortality_alert_threshold_percent', sa.Numeric(precision=5, scale=2),
            nullable=False, server_default='3',
        ))
        batch_op.add_column(sa.Column(
            'sanitary_reminder_interval_minutes', sa.Integer(), nullable=False, server_default='10',
        ))
        batch_op.add_column(sa.Column(
            'email_alerts_enabled', sa.Boolean(), nullable=False, server_default=sa.true(),
        ))
        batch_op.add_column(sa.Column('default_stock_low_threshold', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('default_labor_cost_per_day', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column(
            'default_sale_unit', sa.String(length=10), nullable=False, server_default='unit',
        ))
        batch_op.add_column(sa.Column(
            'max_login_attempts', sa.Integer(), nullable=False, server_default='5',
        ))
        batch_op.add_column(sa.Column(
            'login_lockout_minutes', sa.Integer(), nullable=False, server_default='15',
        ))
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('mortality_alert_threshold_percent', server_default=None)
        batch_op.alter_column('sanitary_reminder_interval_minutes', server_default=None)
        batch_op.alter_column('email_alerts_enabled', server_default=None)
        batch_op.alter_column('default_sale_unit', server_default=None)
        batch_op.alter_column('max_login_attempts', server_default=None)
        batch_op.alter_column('login_lockout_minutes', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('login_lockout_minutes')
        batch_op.drop_column('max_login_attempts')
        batch_op.drop_column('default_sale_unit')
        batch_op.drop_column('default_labor_cost_per_day')
        batch_op.drop_column('default_stock_low_threshold')
        batch_op.drop_column('email_alerts_enabled')
        batch_op.drop_column('sanitary_reminder_interval_minutes')
        batch_op.drop_column('mortality_alert_threshold_percent')
        batch_op.drop_column('fcr_alert_threshold')
        batch_op.drop_column('default_cycle_days')
        batch_op.drop_column('default_breed')

    # ### end Alembic commands ###
