"""ajout ml_per_unit sur stock items pour medicaments liquides

Revision ID: 1e9dcae62416
Revises: f262efbb9900
Create Date: 2026-09-15 06:37:54.232631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9dcae62416'
down_revision = 'f262efbb9900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_stock_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_per_unit', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_stock_items', schema=None) as batch_op:
        batch_op.drop_column('ml_per_unit')

    # ### end Alembic commands ###
