"""ajoute suivi des achats de stock (depenses)

Revision ID: 216a2d9f63a8
Revises: 1b2bb701dce2
Create Date: 2026-09-16 00:58:59.604058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216a2d9f63a8'
down_revision = '1b2bb701dce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poultry_stock_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['poultry_stock_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_stock_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_stock_purchases_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_stock_purchases_stock_item_id'), ['stock_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_stock_purchases_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_stock_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_stock_purchases_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_stock_purchases_stock_item_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_stock_purchases_farm_id'))

    op.drop_table('poultry_stock_purchases')
    # ### end Alembic commands ###
