"""ajout langue preferee sur utilisateurs

Revision ID: 3ebd7cf8490e
Revises: 05fdca745466
Create Date: 2026-09-15 14:08:07.993507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebd7cf8490e'
down_revision = '05fdca745466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('preferred_language', sa.String(length=5), nullable=False, server_default='fr')
        )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('preferred_language', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')

    # ### end Alembic commands ###
