"""Ajout du module de facturation (plans, abonnements, paiements)

Revision ID: 425ad3439538
Revises: 7d17c0b69c13
Create Date: 2026-09-11 00:27:22.045918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425ad3439538'
down_revision = '7d17c0b69c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price_xaf', sa.Integer(), nullable=False),
    sa.Column('billing_period_days', sa.Integer(), nullable=False),
    sa.Column('max_farms', sa.Integer(), nullable=True),
    sa.Column('max_active_batches', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('billing_payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('amount_xaf', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_payment_transactions_provider_transaction_id'), ['provider_transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_billing_payment_transactions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('billing_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_subscriptions_tenant_id'), ['tenant_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_subscriptions_tenant_id'))

    op.drop_table('billing_subscriptions')
    with op.batch_alter_table('billing_payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_payment_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_billing_payment_transactions_provider_transaction_id'))

    op.drop_table('billing_payment_transactions')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
