"""Ajout ON DELETE SET NULL sur les FK vers users et growth_references

Revision ID: 4be04d5aaaa8
Revises: b7ca0508da24
Create Date: 2026-09-11 02:21:01.831995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be04d5aaaa8'
down_revision = 'b7ca0508da24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_batches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_batches_growth_reference_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('poultry_batches_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'poultry_growth_references', ['growth_reference_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_daily_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_daily_reports_submitted_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('poultry_daily_reports_reviewed_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['submitted_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_feed_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_feed_records_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_growth_references', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_growth_references_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_medication_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_medication_records_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_mortality_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_mortality_records_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_observations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_observations_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_sanitary_program_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_sanitary_program_items_done_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['done_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_water_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_water_records_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_weight_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_weight_records_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_wood_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_wood_records_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_wood_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_wood_records_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('poultry_weight_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_weight_records_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('poultry_water_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_water_records_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('poultry_sanitary_program_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_sanitary_program_items_done_by_fkey'), 'users', ['done_by'], ['id'])

    with op.batch_alter_table('poultry_observations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_observations_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('poultry_mortality_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_mortality_records_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('poultry_medication_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_medication_records_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('poultry_growth_references', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_growth_references_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('poultry_feed_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_feed_records_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('poultry_daily_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_daily_reports_reviewed_by_fkey'), 'users', ['reviewed_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('poultry_daily_reports_submitted_by_fkey'), 'users', ['submitted_by'], ['id'])

    with op.batch_alter_table('poultry_batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_batches_created_by_fkey'), 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('poultry_batches_growth_reference_id_fkey'), 'poultry_growth_references', ['growth_reference_id'], ['id'])

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_log_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
