"""ON DELETE SET NULL sur audit_log.tenant_id

Revision ID: 57d4fbbcd1ff
Revises: 4be04d5aaaa8
Create Date: 2026-09-11 02:25:43.400350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d4fbbcd1ff'
down_revision = '4be04d5aaaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_log_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_log_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###
