"""courbe de ponte attendue et age des poules

Revision ID: 7ce32f1e0815
Revises: dec5581cf42a
Create Date: 2026-09-20 01:17:07.653469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce32f1e0815'
down_revision = 'dec5581cf42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_age_weeks', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('laying_reference_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_poultry_batches_laying_reference', 'poultry_growth_references', ['laying_reference_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_growth_references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=10), server_default='weight', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_growth_references', schema=None) as batch_op:
        batch_op.drop_column('kind')

    with op.batch_alter_table('poultry_batches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_poultry_batches_laying_reference', type_='foreignkey')
        batch_op.drop_column('laying_reference_id')
        batch_op.drop_column('start_age_weeks')

    # ### end Alembic commands ###
