"""ajout parametres generaux du tenant (pays, langue, devise)

Revision ID: 956949e92fad
Revises: 3ebd7cf8490e
Create Date: 2026-09-15 15:02:46.947663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956949e92fad'
down_revision = '3ebd7cf8490e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=True))
        batch_op.add_column(
            sa.Column('default_language', sa.String(length=5), nullable=False, server_default='fr')
        )
        batch_op.add_column(
            sa.Column('currency_label', sa.String(length=10), nullable=False, server_default='FCFA')
        )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('default_language', server_default=None)
        batch_op.alter_column('currency_label', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('currency_label')
        batch_op.drop_column('default_language')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
