"""ondelete set null sur stock_item_id des enregistrements

Revision ID: a3543940189d
Revises: 1e9dcae62416
Create Date: 2026-09-15 07:00:30.983898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3543940189d'
down_revision = '1e9dcae62416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_feed_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_feed_records_stock_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'poultry_stock_items', ['stock_item_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_medication_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_medication_records_stock_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'poultry_stock_items', ['stock_item_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poultry_wood_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poultry_wood_records_stock_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'poultry_stock_items', ['stock_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_wood_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_wood_records_stock_item_id_fkey'), 'poultry_stock_items', ['stock_item_id'], ['id'])

    with op.batch_alter_table('poultry_medication_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_medication_records_stock_item_id_fkey'), 'poultry_stock_items', ['stock_item_id'], ['id'])

    with op.batch_alter_table('poultry_feed_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('poultry_feed_records_stock_item_id_fkey'), 'poultry_stock_items', ['stock_item_id'], ['id'])

    # ### end Alembic commands ###
