"""Ajout de la limite quotidienne de messages par plan

Revision ID: b1de3f3c2b13
Revises: 099619ee9090
Create Date: 2026-09-13 22:58:05.841155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1de3f3c2b13'
down_revision = '099619ee9090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_messages_per_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_plans', schema=None) as batch_op:
        batch_op.drop_column('max_messages_per_day')

    # ### end Alembic commands ###
