"""Schema initial Farm Control v1.1

Revision ID: b7ca0508da24
Revises: 
Create Date: 2026-09-11 01:59:34.011637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ca0508da24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'farm_id', 'category', 'name', name='uq_stockitem_tenant_farm_cat_name')
    )
    with op.batch_alter_table('poultry_stock_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_stock_items_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_stock_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('poultry_growth_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_growth_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_growth_references_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('initial_count', sa.Integer(), nullable=False),
    sa.Column('chick_unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('growth_reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['growth_reference_id'], ['poultry_growth_references.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'farm_id', 'code', name='uq_batch_tenant_farm_code')
    )
    with op.batch_alter_table('poultry_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_batches_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_batches_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_growth_reference_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('expected_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['poultry_growth_references.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id', 'day_number', name='uq_growthpoint_ref_day')
    )
    with op.batch_alter_table('poultry_growth_reference_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_growth_reference_points_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_growth_reference_points_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_batch_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'day_number', name='uq_batchday_batch_daynumber')
    )
    with op.batch_alter_table('poultry_batch_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_batch_days_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_batch_days_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_batch_finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('chick_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_feed_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_medication_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_wood_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_quantity', sa.Integer(), nullable=True),
    sa.Column('sale_unit', sa.String(length=10), nullable=False),
    sa.Column('sale_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_result', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_batch_finance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_batch_finance_batch_id'), ['batch_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_poultry_batch_finance_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_sanitary_program_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('program_type', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['done_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_sanitary_program_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_sanitary_program_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_sanitary_program_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_day_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_day_id'], ['poultry_batch_days.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_daily_reports_batch_day_id'), ['batch_day_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_poultry_daily_reports_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_daily_reports_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_feed_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_day_id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('feed_type', sa.String(length=100), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_day_id'], ['poultry_batch_days.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['poultry_stock_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_feed_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_feed_records_batch_day_id'), ['batch_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_feed_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_feed_records_stock_item_id'), ['stock_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_feed_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_medication_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_day_id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('medication_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_day_id'], ['poultry_batch_days.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['poultry_stock_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_medication_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_medication_records_batch_day_id'), ['batch_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_medication_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_medication_records_stock_item_id'), ['stock_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_medication_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_mortality_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_day_id', sa.Integer(), nullable=False),
    sa.Column('quantity_dead', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_day_id'], ['poultry_batch_days.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_mortality_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_mortality_records_batch_day_id'), ['batch_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_mortality_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_mortality_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_day_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_day_id'], ['poultry_batch_days.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_observations_batch_day_id'), ['batch_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_observations_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_observations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_water_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_day_id', sa.Integer(), nullable=False),
    sa.Column('quantity_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_day_id'], ['poultry_batch_days.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_water_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_water_records_batch_day_id'), ['batch_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_water_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_water_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_weight_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_day_id', sa.Integer(), nullable=False),
    sa.Column('average_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_day_id'], ['poultry_batch_days.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_weight_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_weight_records_batch_day_id'), ['batch_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_weight_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_weight_records_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_weight_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_wood_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_day_id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_day_id'], ['poultry_batch_days.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['poultry_stock_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_wood_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_wood_records_batch_day_id'), ['batch_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_wood_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_wood_records_stock_item_id'), ['stock_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_wood_records_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_wood_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_wood_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_wood_records_stock_item_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_wood_records_batch_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_wood_records_batch_day_id'))

    op.drop_table('poultry_wood_records')
    with op.batch_alter_table('poultry_weight_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_weight_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_weight_records_farm_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_weight_records_batch_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_weight_records_batch_day_id'))

    op.drop_table('poultry_weight_records')
    with op.batch_alter_table('poultry_water_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_water_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_water_records_batch_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_water_records_batch_day_id'))

    op.drop_table('poultry_water_records')
    with op.batch_alter_table('poultry_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_observations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_observations_batch_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_observations_batch_day_id'))

    op.drop_table('poultry_observations')
    with op.batch_alter_table('poultry_mortality_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_mortality_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_mortality_records_batch_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_mortality_records_batch_day_id'))

    op.drop_table('poultry_mortality_records')
    with op.batch_alter_table('poultry_medication_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_medication_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_medication_records_stock_item_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_medication_records_batch_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_medication_records_batch_day_id'))

    op.drop_table('poultry_medication_records')
    with op.batch_alter_table('poultry_feed_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_feed_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_feed_records_stock_item_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_feed_records_batch_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_feed_records_batch_day_id'))

    op.drop_table('poultry_feed_records')
    with op.batch_alter_table('poultry_daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_daily_reports_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_daily_reports_batch_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_daily_reports_batch_day_id'))

    op.drop_table('poultry_daily_reports')
    with op.batch_alter_table('poultry_sanitary_program_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_sanitary_program_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_sanitary_program_items_batch_id'))

    op.drop_table('poultry_sanitary_program_items')
    with op.batch_alter_table('poultry_batch_finance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_batch_finance_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_batch_finance_batch_id'))

    op.drop_table('poultry_batch_finance')
    with op.batch_alter_table('poultry_batch_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_batch_days_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_batch_days_batch_id'))

    op.drop_table('poultry_batch_days')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_farm_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_batch_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('poultry_growth_reference_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_growth_reference_points_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_growth_reference_points_reference_id'))

    op.drop_table('poultry_growth_reference_points')
    with op.batch_alter_table('poultry_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_batches_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_batches_farm_id'))

    op.drop_table('poultry_batches')
    with op.batch_alter_table('poultry_growth_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_growth_references_tenant_id'))

    op.drop_table('poultry_growth_references')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_tenant_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_farm_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('poultry_stock_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_stock_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_stock_items_farm_id'))

    op.drop_table('poultry_stock_items')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_tenant_id'))

    op.drop_table('farms')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
