"""ajout fournisseurs et ventes multiples par lot

Revision ID: d2e4c7780d5b
Revises: a3543940189d
Create Date: 2026-09-15 12:37:40.779478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e4c7780d5b'
down_revision = 'a3543940189d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poultry_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_suppliers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('poultry_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('buyer_name', sa.String(length=150), nullable=False),
    sa.Column('buyer_phone', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_sales_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_sales_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('poultry_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_poultry_batches_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_foreign_key(None, 'poultry_suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_poultry_batches_supplier_id'))
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('poultry_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_sales_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_sales_batch_id'))

    op.drop_table('poultry_sales')
    with op.batch_alter_table('poultry_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_suppliers_tenant_id'))

    op.drop_table('poultry_suppliers')
    # ### end Alembic commands ###
