"""ajoute les oeufs (poules pondeuses)

Revision ID: dec5581cf42a
Revises: a3c1e5d7b902
Create Date: 2026-09-20 00:52:42.104736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec5581cf42a'
down_revision = 'a3c1e5d7b902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poultry_egg_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_day_id', sa.Integer(), nullable=False),
    sa.Column('eggs_collected', sa.Integer(), nullable=False),
    sa.Column('eggs_broken', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_day_id'], ['poultry_batch_days.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poultry_egg_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poultry_egg_records_batch_day_id'), ['batch_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_egg_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poultry_egg_records_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_egg_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poultry_egg_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_egg_records_batch_id'))
        batch_op.drop_index(batch_op.f('ix_poultry_egg_records_batch_day_id'))

    op.drop_table('poultry_egg_records')
    # ### end Alembic commands ###
