"""ajout kg_per_unit sur stock items

Revision ID: e637d6a15b76
Revises: b1de3f3c2b13
Create Date: 2026-09-14 05:24:48.044175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e637d6a15b76'
down_revision = 'b1de3f3c2b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_stock_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kg_per_unit', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_stock_items', schema=None) as batch_op:
        batch_op.drop_column('kg_per_unit')

    # ### end Alembic commands ###
