"""ajout granted_by_admin sur abonnements

Revision ID: f262efbb9900
Revises: e637d6a15b76
Create Date: 2026-09-15 06:00:21.472364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f262efbb9900'
down_revision = 'e637d6a15b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust ###
    # server_default requis pour remplir les lignes existantes, puis retire
    # (le modele ne definit un defaut que cote application, pas en base).
    with op.batch_alter_table('billing_subscriptions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('granted_by_admin', sa.Boolean(), nullable=False, server_default=sa.false())
        )
    with op.batch_alter_table('billing_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('granted_by_admin', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('granted_by_admin')

    # ### end Alembic commands ###
