"""unite d'affichage des courbes de poids

Revision ID: fd529ebc8880
Revises: 248c5526dda0
Create Date: 2026-09-20 05:08:28.785921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd529ebc8880'
down_revision = '248c5526dda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_growth_references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_unit', sa.String(length=3), server_default='g', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poultry_growth_references', schema=None) as batch_op:
        batch_op.drop_column('display_unit')

    # ### end Alembic commands ###
